version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      all-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - ci
    commit-message:
      prefix: chore
      include: scope
