package main

import (
	"os"
	"path/filepath"
	"testing"
)

func writeAndReorder(t *testing.T, src string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), "file.go")
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	if _, err := reorderFile(path); err != nil {
		t.Fatalf("reorderFile: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	return string(got)
}

func TestReorderFuncsEntrypointFirst(t *testing.T) {
	t.Parallel()

	src := `package ui

func aboutPage() {
}

func Build() {
}

func homePage() {
}
`
	want := `package ui

func Build() {
}

func aboutPage() {
}

func homePage() {
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderFuncsExportedBeforeUnexported(t *testing.T) {
	t.Parallel()

	src := `package ui

func helper() {
}

func Exported() {
}
`
	want := `package ui

func Exported() {
}

func helper() {
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderPreservesDocComments(t *testing.T) {
	t.Parallel()

	src := `package ui

// helper does the thing.
func helper() {
}

// Exported does the exported thing.
func Exported() {
}
`
	want := `package ui

// Exported does the exported thing.
func Exported() {
}

// helper does the thing.
func helper() {
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderStableWithinGroup(t *testing.T) {
	t.Parallel()

	// Two unexported funcs interleaved with two exported ones: within each
	// group, relative order must be preserved.
	src := `package ui

func b() {
}

func B() {
}

func a() {
}

func A() {
}
`
	want := `package ui

func B() {
}

func A() {
}

func b() {
}

func a() {
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderDoesNotCrossNonFuncDecl(t *testing.T) {
	t.Parallel()

	// A var block splits the file into two independent func runs; each run
	// reorders on its own (exported before unexported), but funcs must never
	// move across the var boundary into the other run.
	src := `package ui

func b() {
}

func A() {
}

var x = 1

func d() {
}

func C() {
}
`
	want := `package ui

func A() {
}

func b() {
}

var x = 1

func C() {
}

func d() {
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderLeavesAlreadyOrderedFileUntouched(t *testing.T) {
	t.Parallel()

	src := `package ui

func Build() {
}

func Exported() {
}

func helper() {
}
`

	path := filepath.Join(t.TempDir(), "file.go")
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	changed, err := reorderFile(path)
	if err != nil {
		t.Fatalf("reorderFile: %v", err)
	}
	if changed {
		t.Error("reorderFile reported a change on an already-ordered file")
	}
}

func TestReorderSkipsGeneratedFiles(t *testing.T) {
	t.Parallel()

	src := `// Code generated by somegen; DO NOT EDIT.
package ui

func b() {
}

func a() {
}
`

	path := filepath.Join(t.TempDir(), "file.go")
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	changed, err := reorderFile(path)
	if err != nil {
		t.Fatalf("reorderFile: %v", err)
	}
	if changed {
		t.Error("reorderFile modified a generated file")
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != src {
		t.Errorf("generated file content changed:\n%s", got)
	}
}

func TestReorderRouterMapByPath(t *testing.T) {
	t.Parallel()

	src := `package ui

func Build(ctx *fugo.Context) fg.Widget {
	return fg.Router(map[string]func() fg.Widget{
		"/settings": func() fg.Widget { return settingsPage(ctx) },
		"/":         func() fg.Widget { return homePage(ctx) },
		"/about":    func() fg.Widget { return aboutPage(ctx) },
	}, "/")
}
`
	want := `package ui

func Build(ctx *fugo.Context) fg.Widget {
	return fg.Router(map[string]func() fg.Widget{
		"/":         func() fg.Widget { return homePage(ctx) },
		"/about":    func() fg.Widget { return aboutPage(ctx) },
		"/settings": func() fg.Widget { return settingsPage(ctx) },
	}, "/")
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderRouterMapKeepsCommentWithEntry(t *testing.T) {
	t.Parallel()

	src := `package ui

func Build(ctx *fugo.Context) fg.Widget {
	return fg.Router(map[string]func() fg.Widget{
		"/settings": func() fg.Widget { return settingsPage(ctx) },
		// home page
		"/": func() fg.Widget { return homePage(ctx) },
	}, "/")
}
`
	want := `package ui

func Build(ctx *fugo.Context) fg.Widget {
	return fg.Router(map[string]func() fg.Widget{
		// home page
		"/": func() fg.Widget { return homePage(ctx) },
		"/settings": func() fg.Widget { return settingsPage(ctx) },
	}, "/")
}
`
	if got := writeAndReorder(t, src); got != want {
		t.Errorf("got:\n%s\nwant:\n%s", got, want)
	}
}

func TestReorderSkipsComputedRouterKeys(t *testing.T) {
	t.Parallel()

	src := `package ui

func Build(ctx *fugo.Context) fg.Widget {
	key := "/dynamic"

	return fg.Router(map[string]func() fg.Widget{
		"/settings": func() fg.Widget { return settingsPage(ctx) },
		key:         func() fg.Widget { return dynamicPage(ctx) },
		"/about":    func() fg.Widget { return aboutPage(ctx) },
	}, "/")
}
`

	path := filepath.Join(t.TempDir(), "file.go")
	if err := os.WriteFile(path, []byte(src), 0o600); err != nil {
		t.Fatal(err)
	}

	changed, err := reorderFile(path)
	if err != nil {
		t.Fatalf("reorderFile: %v", err)
	}
	if changed {
		t.Error("reorderFile touched a Router map with a computed key")
	}
}
