// Command gen-icons regenerates the Material icon name table from the Flutter
// SDK. It parses material/icons.dart, keeps the base icon family (dropping the
// _sharp / _rounded / _outlined variants), and writes two committed files:
//
//   - fg/icons_gen.go               the fg.Icons set (fg.Icons.Home == "home")
//   - flutter_client/lib/icons_gen.dart   the name -> IconData runtime map
//
// The Go side carries the icon's Flutter field name; the Dart side resolves it
// to the real Flutter Icons constant (so directional icons keep their RTL
// behavior). Run from the repo root:
//
//	go run ./cmd/gen-icons [path/to/material/icons.dart]
//
// With no argument it locates icons.dart from the `flutter` command on PATH.
package main

import (
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-icons:", err)
		os.Exit(1)
	}
}

func run() error {
	path, err := iconsPath()
	if err != nil {
		return err
	}

	src, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read %s: %w", path, err)
	}

	names := baseIconNames(string(src))
	if len(names) == 0 {
		return fmt.Errorf("no IconData declarations found in %s", path)
	}

	if err := writeGo(names); err != nil {
		return err
	}

	if err := writeDart(names); err != nil {
		return err
	}

	fmt.Printf("gen-icons: wrote %d base icons to fg/icons_gen.go and flutter_client/lib/icons_gen.dart\n", len(names))

	return nil
}

// iconsPath returns the CLI argument if given, otherwise resolves icons.dart
// from the Flutter SDK that owns the `flutter` command on PATH.
func iconsPath() (string, error) {
	if len(os.Args) > 1 {
		return os.Args[1], nil
	}

	bin, err := exec.LookPath("flutter")
	if err != nil {
		return "", fmt.Errorf("flutter not on PATH; pass the icons.dart path explicitly: %w", err)
	}

	if resolved, err := filepath.EvalSymlinks(bin); err == nil {
		bin = resolved
	}

	root := filepath.Dir(filepath.Dir(bin)) // <sdk>/bin/flutter -> <sdk>

	return filepath.Join(root, "packages", "flutter", "lib", "src", "material", "icons.dart"), nil
}

var iconDecl = regexp.MustCompile(`static const IconData (\w+) = IconData\(`)

// baseIconNames extracts the base icon family from icons.dart, sorted and
// de-duplicated. Variant families (_sharp/_rounded/_outlined) are dropped.
func baseIconNames(src string) []string {
	seen := map[string]bool{}

	var names []string

	for _, m := range iconDecl.FindAllStringSubmatch(src, -1) {
		name := m[1]
		if strings.HasSuffix(name, "_sharp") || strings.HasSuffix(name, "_rounded") || strings.HasSuffix(name, "_outlined") {
			continue
		}

		if seen[name] {
			continue
		}

		seen[name] = true
		names = append(names, name)
	}

	sort.Strings(names)

	return names
}

// goField converts a Flutter icon name (snake_case) to an exported Go field
// name (PascalCase): "arrow_back" -> "ArrowBack", "ten_k" -> "TenK".
func goField(name string) string {
	var b strings.Builder

	for _, part := range strings.Split(name, "_") {
		if part == "" {
			continue
		}

		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}

	return b.String()
}

func writeGo(names []string) error {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/gen-icons; DO NOT EDIT.\n\n")
	b.WriteString("package fg\n\n")
	b.WriteString("// iconSet is the Material icon name table. Access an icon through the Icons\n")
	b.WriteString("// var, e.g. fg.Icons.Home — the Flutter equivalent of Icons.home. Each field\n")
	b.WriteString("// holds the icon's Flutter name, which the render client resolves to its\n")
	b.WriteString("// IconData. Pass one to fg.Icon, fg.IconButton, fg.FloatingActionButton, etc.\n")
	b.WriteString("type iconSet struct {\n")

	fields := map[string]string{} // goField -> name, for collision detection

	var ordered []string

	for _, name := range names {
		f := goField(name)
		if _, dup := fields[f]; dup {
			continue
		}

		fields[f] = name
		ordered = append(ordered, f)
	}

	sort.Strings(ordered)
	for _, f := range ordered {
		fmt.Fprintf(&b, "\t%s string\n", f)
	}

	b.WriteString("}\n\n")
	b.WriteString("// Icons is the Material icon set, mirroring Flutter's Icons (fg.Icons.Home).\n")
	b.WriteString("var Icons = iconSet{\n")

	for _, f := range ordered {
		fmt.Fprintf(&b, "\t%s: %q,\n", f, fields[f])
	}

	b.WriteString("}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format generated Go: %w", err)
	}

	return os.WriteFile(filepath.Join("fg", "icons_gen.go"), formatted, 0o644)
}

func writeDart(names []string) error {
	var b strings.Builder

	b.WriteString("// Code generated by cmd/gen-icons; DO NOT EDIT.\n")
	b.WriteString("import 'package:flutter/material.dart';\n\n")
	b.WriteString("// materialIcons resolves an fg icon name (fg.Icons.Home -> 'home') to the\n")
	b.WriteString("// matching Flutter IconData, preserving each icon's built-in direction.\n")
	b.WriteString("const Map<String, IconData> materialIcons = {\n")

	for _, name := range names {
		fmt.Fprintf(&b, "  %q: Icons.%s,\n", name, name)
	}

	b.WriteString("};\n")

	return os.WriteFile(filepath.Join("flutter_client", "lib", "icons_gen.dart"), []byte(b.String()), 0o644)
}
