// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: transport/proto/fugo/v1/fugo.proto

package fugov1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FugoRender_RenderStream_FullMethodName = "/fugo.v1.FugoRender/RenderStream"
)

// FugoRenderClient is the client API for FugoRender service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FugoRenderClient interface {
	RenderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientEvent, RenderPayload], error)
}

type fugoRenderClient struct {
	cc grpc.ClientConnInterface
}

func NewFugoRenderClient(cc grpc.ClientConnInterface) FugoRenderClient {
	return &fugoRenderClient{cc}
}

func (c *fugoRenderClient) RenderStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientEvent, RenderPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FugoRender_ServiceDesc.Streams[0], FugoRender_RenderStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientEvent, RenderPayload]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FugoRender_RenderStreamClient = grpc.BidiStreamingClient[ClientEvent, RenderPayload]

// FugoRenderServer is the server API for FugoRender service.
// All implementations must embed UnimplementedFugoRenderServer
// for forward compatibility.
type FugoRenderServer interface {
	RenderStream(grpc.BidiStreamingServer[ClientEvent, RenderPayload]) error
	mustEmbedUnimplementedFugoRenderServer()
}

// UnimplementedFugoRenderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFugoRenderServer struct{}

func (UnimplementedFugoRenderServer) RenderStream(grpc.BidiStreamingServer[ClientEvent, RenderPayload]) error {
	return status.Error(codes.Unimplemented, "method RenderStream not implemented")
}
func (UnimplementedFugoRenderServer) mustEmbedUnimplementedFugoRenderServer() {}
func (UnimplementedFugoRenderServer) testEmbeddedByValue()                    {}

// UnsafeFugoRenderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FugoRenderServer will
// result in compilation errors.
type UnsafeFugoRenderServer interface {
	mustEmbedUnimplementedFugoRenderServer()
}

func RegisterFugoRenderServer(s grpc.ServiceRegistrar, srv FugoRenderServer) {
	// If the following call panics, it indicates UnimplementedFugoRenderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FugoRender_ServiceDesc, srv)
}

func _FugoRender_RenderStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FugoRenderServer).RenderStream(&grpc.GenericServerStream[ClientEvent, RenderPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FugoRender_RenderStreamServer = grpc.BidiStreamingServer[ClientEvent, RenderPayload]

// FugoRender_ServiceDesc is the grpc.ServiceDesc for FugoRender service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FugoRender_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fugo.v1.FugoRender",
	HandlerType: (*FugoRenderServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RenderStream",
			Handler:       _FugoRender_RenderStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transport/proto/fugo/v1/fugo.proto",
}
